import { useAppointmentState } from "@/hooks/useAppointmentState";
export const {
    appointment, setAppointment,
    invoices, setInvoices,
    expandedInvoice, setExpandedInvoice,
    invoiceToEdit, setInvoiceToEdit,
    invoiceItems, setInvoiceItems,
    isInvoiceModalOpen, setIsInvoiceModalOpen,
    isAppointmentStatusModalOpen, setIsAppointmentStatusModalOpen,
    invoiceDueDate, setInvoiceDueDate,
    invoiceTax, setInvoiceTax,
    invoiceNotes, setInvoiceNotes,
    isNoteModalOpen, setIsNoteModalOpen,
    noteToEdit, setNoteToEdit,
    newNote, setNewNote,
    isPaymentModalOpen, setIsPaymentModalOpen,
    selectedInvoiceId, setSelectedInvoiceId,
    isRescheduleModalOpen, setIsRescheduleModalOpen,
    newDate, setNewDate,
    newTime, setNewTime,
    availableSlots, setAvailableSlots,
    isLoadingSlots, setIsLoadingSlots,
    paymentToDelete, setPaymentToDelete,
    deletingId, setDeletingId,
    invoiceToDelete, setInvoiceToDelete,
    deletingInvoiceId, setDeletingInvoiceId,
    noteToDelete, setNoteToDelete,
    deletingNoteId, setDeletingNoteId,
    deletingFileId, setDeletingFileId,
    fileToDelete, setFileToDelete,
    isFileModalOpen, setIsFileModalOpen
  } = useAppointmentState();
